PRODUCT_RESTRICT_VENDOR_FILES := false
PRODUCT_ENFORCE_VINTF_MANIFEST := false
PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true
PRODUCT_SET_DEBUGFS_RESTRICTIONS := false
USES_GOOGLE_DIALER_CARRIER_SETTINGS := true

PRODUCT_NAME := benzo_$(BENZO_DEVICE)
PRODUCT_SYSTEM_NAME := $(BENZO_DEVICE)
PRODUCT_MODEL := $(BENZO_MODEL)
PRODUCT_DEVICE := $(BENZO_DEVICE)
PRODUCT_BRAND := google
PRODUCT_SYSTEM_BRAND := google
PRODUCT_MANUFACTURER := Google
PRODUCT_SYSTEM_MANUFACTURER := Google

PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_NAME=$(BENZO_DEVICE) \
    PRIVATE_BUILD_DESC=$(BENZO_BUILD_DESC)

BUILD_FINGERPRINT=$(BENZO_FINGERPRINT)
BUILD_THUMBPRINT=$(BENZO_THUMBPRINT)
